Sanitario/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Sanitario.Data;
using Sanitario.Models;
using System.Security.Claims;

namespace Sanitario.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAuthenticationSchemeProvider _schemeProvider;
        public LoginController(ApplicationDbContext context, IAuthenticationSchemeProvider schemeProvider)
        {
            _context = context;
            _schemeProvider = schemeProvider;
        }
        public IActionResult Index()
        {
            return View();
        }

        [ActionName("Index")]
        [HttpPost]
        public async Task<IActionResult> Login(Dipendente dipendente)
        {
            // Query per trovare l'dipendente nel db
            var dbUser = _context.Dipendenti.FirstOrDefault(d => d.Username == dipendente.Username);

            // Se la query non trova niente ci restituisce il temp data da stampare nella view
            if (dbUser == null)
            {
                TempData["error"] = "Questo Nome Utente non esiste";
                return View();
            }
            if (dbUser.Password != dipendente.Password)
            {
                TempData["error"] = "Credenziali non valide";
                return View();
            }
            // Trovato l'dipendente, se la password che inseriamo coincide con quella presente sul db possiamo procedere
            // Salviamo nei claims le informazioni sull'dipendente autenticato
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, dbUser.Username),
                new Claim(ClaimTypes.Role, dbUser.Ruolo),
                new Claim(ClaimTypes.NameIdentifier, dbUser.IdDipendente.ToString())
            };
            // Salviamo in questa variabile l'identità dell'dipendente autenticato
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
            TempData["success"] = "Login effettuato con successo";

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            TempData["success"] = "Logout effettuato con successo";
            return RedirectToAction("Index", "Home");
        }
    }
}

Sanitario/Controllers/ProdottoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sanitario.Data;
using Sanitario.Models;

namespace Sanitario.Controllers
{
    [Authorize(Roles = "Admin, Farmacista")]
    public class ProdottoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProdottoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Prodotto
        public async Task<IActionResult> Index()
        {
            var prodotti = await _context.Prodotti
                            .Include(p => p.Cassetto)
                            .ThenInclude(c => c.Armadietto)
                            .ToListAsync();

            return View(prodotti);
        }

        // GET: Prodotto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prodotto = await _context.Prodotti
                .FirstOrDefaultAsync(m => m.IdProdotto == id);
            if (prodotto == null)
            {
                return NotFound();
            }

            return View(prodotto);
        }

        // GET: Prodotto/Create
        public IActionResult Create()
        {
            ViewBag.Cassetti = _context.Cassetti.Select(c => new SelectListItem
            {
                Value = c.IdCassetto.ToString(),
                Text = $"Cassetto: {c.NumeroCassetto} - Armadietto: {c.Armadietto.NumeroArmadietto}"
            }).ToList();
            return View();
        }

        // POST: Prodotto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,Descrizione,Prezzo, TipoProdotto, IdCassetto")] Prodotto prodotto)
        {
            ModelState.Remove("DettagliVendite");
            ModelState.Remove("CurePrescritte");
            ModelState.Remove("Cassetto");
            if (ModelState.IsValid)
            {
                _context.Add(prodotto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Cassetti = new SelectList(_context.Cassetti, "IdCassetto", "NomeCassetto");
            return View(prodotto);
        }

        // GET: Prodotto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prodotto = await _context.Prodotti.FindAsync(id);
            if (prodotto == null)
            {
                return NotFound();
            }
            return View(prodotto);
        }

        // POST: Prodotto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdProdotto,Nome,Descrizione,Prezzo")] Prodotto prodotto)
        {
            if (id != prodotto.IdProdotto)
            {
                return NotFound();
            }

            ModelState.Remove("DettagliVendite");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(prodotto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdottoExists(prodotto.IdProdotto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(prodotto);
        }

        // GET: Prodotto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prodotto = await _context.Prodotti
                .FirstOrDefaultAsync(m => m.IdProdotto == id);
            if (prodotto == null)
            {
                return NotFound();
            }

            return View(prodotto);
        }

        // POST: Prodotto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var prodotto = await _context.Prodotti.FindAsync(id);
            if (prodotto != null)
            {
                _context.Prodotti.Remove(prodotto);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdottoExists(int id)
        {
            return _context.Prodotti.Any(e => e.IdProdotto == id);
        }

        // Questo l'ho messo per testare da postman
        [AllowAnonymous]
        public async Task<IActionResult> SearchMedicinale(string medicinale)
        {

            var prodotto = await _context.Prodotti
                .Where(p => p.TipoProdotto == "Medicinale" && p.Nome.Contains(medicinale))
                .Select(p => new
                {
                    p.IdProdotto,
                    p.Nome,
                    p.Descrizione,
                    p.Prezzo,
                    p.TipoProdotto,
                    Armadietto = new
                    {
                        numeroArmadietto = p.Cassetto.Armadietto.NumeroArmadietto,
                        numeroCassetto = p.Cassetto.NumeroCassetto
                    }
                })
                .ToListAsync();


            if (prodotto == null)
            {
                return NotFound();
            }
            return Json(prodotto);
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetMedicinaleByDate(DateOnly data)
        {
            var listMedicinali = await _context.Prodotti
                .Where(p => p.TipoProdotto == "Medicinale" && p.DettagliVendite.Any(d => DateOnly.FromDateTime(d.Vendita.DataVendita.Date) == data))
                .Select(p => new
                {
                    p.IdProdotto,
                    p.Nome,
                    p.Descrizione,
                    p.Prezzo,
                    p.TipoProdotto
                })
                .ToListAsync();
            return Json(listMedicinali);

        }

        [AllowAnonymous]
        public async Task<IActionResult> GetMedicinaliByCF(string codiceFiscale)
        {
            var listMedicinali = await _context.Prodotti
                .Where(p => p.TipoProdotto == "Medicinale" && p.DettagliVendite.Any(d => d.Vendita.Cliente.CodiceFiscale == codiceFiscale))
                .Select(p => new
                {
                    p.IdProdotto,
                    p.Nome,
                    p.Descrizione,
                    p.Prezzo,
                    p.TipoProdotto
                })
                .ToListAsync();
            return Json(listMedicinali);
        }
    }
}

Sanitario/Controllers/VisitaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sanitario.Data;
using Sanitario.Models;

namespace Sanitario.Controllers
{
    [Authorize(Roles = "Admin, Veterinario")]
    public class VisitaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VisitaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Visita
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Visite.Include(v => v.Animale).ThenInclude(a => a.Cliente);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Visita/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visita = await _context.Visite
                .Include(v => v.Animale)
                .ThenInclude(a => a.Cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visita == null)
            {
                return NotFound();
            }

            return View(visita);
        }

        // GET: Visita/Create
        public IActionResult Create()
        {
            ViewData["IdAnimale"] = new SelectList(_context.Animali.Include(a => a.Cliente), "IdAnimale", "NomeCompleto");
            ViewBag.ListaMedicinali = new MultiSelectList(_context.Prodotti.Where(p => p.TipoProdotto == "Medicinale"), "IdProdotto", "Nome");
            return View();
        }



        // POST: Visita/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAnimale,DataVisita,Esame")] Visita visita, List<int> medicinaliSelezionati)
        {
            ModelState.Remove("CurePrescritte");
            ModelState.Remove("Animale");
            if (ModelState.IsValid)
            {
                visita.CurePrescritte = new List<CuraPrescritta>();
                _context.Add(visita);
                await _context.SaveChangesAsync();
                foreach (var idMedicinale in medicinaliSelezionati)
                {
                    var curaPrescritta = new CuraPrescritta { IdProdotto = idMedicinale, IdVisita = visita.Id };
                    _context.Add(curaPrescritta);

                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAnimale"] = new SelectList(_context.Animali.Include(a => a.Cliente), "IdAnimale", "NomeCompleto", visita.IdAnimale);
            ViewBag.ListaMedicinali = new MultiSelectList(_context.Prodotti.Where(p => p.TipoProdotto == "Medicinale"), "IdProdotto", "Nome");
            return View(visita);
        }

        // GET: Visita/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visita = await _context.Visite.FindAsync(id);
            if (visita == null)
            {
                return NotFound();
            }
            ViewData["IdAnimale"] = new SelectList(_context.Animali.Include(a => a.Cliente), "IdAnimale", "NomeCompleto", visita.IdAnimale);
            return View(visita);
        }

        // POST: Visita/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdAnimale,DataVisita,Esame")] Visita visita)
        {
            if (id != visita.Id)
            {
                return NotFound();
            }

            var checkIdAnimale = _context.Animali.AsNoTracking().FirstOrDefault(a => a.IdAnimale == id);
            if (checkIdAnimale.IdAnimale != visita.IdAnimale)
            {
                TempData["error"] = "Non puoi modificare l'ID della visita";

                ViewData["IdAnimale"] = new SelectList(_context.Animali.Include(a => a.Cliente), "IdAnimale", "NomeCompleto", visita.IdAnimale);
                return View(visita);
            }

            ModelState.Remove("CurePrescritte");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(visita);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VisitaExists(visita.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAnimale"] = new SelectList(_context.Animali, "IdAnimale", "ColoreMantello", visita.IdAnimale);
            return View(visita);
        }

        // GET: Visita/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visita = await _context.Visite
                .Include(v => v.Animale)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visita == null)
            {
                return NotFound();
            }

            return View(visita);
        }

        // POST: Visita/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var visita = await _context.Visite.FindAsync(id);
            if (visita != null)
            {
                _context.Visite.Remove(visita);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VisitaExists(int id)
        {
            return _context.Visite.Any(e => e.Id == id);
        }
    }
}

Sanitario/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sanitario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/Sanitario.styles.css" asp-append-version="true" />
</head>
<body class="p-5">
    <div class="mx-5 my-3 rounded bg-white ">
        <div id="mainContainer">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-transparent mb-5">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="/imgs/site/logo.png" width="100" />
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link primaryText" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @{
                                if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link primaryText" asp-area="" asp-controller="Dipendente" asp-action="BackOffice">BackOffice</a>
                                }
                            }
                        </ul>
                        @{
                            if (!User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link primaryText" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            }
                            else
                            {
                                <a class="nav-link primaryText" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            }

                            
                        }
                    </div>
                </div>
            </nav>
            <div class="container">
                <main role="main" class="py-3">
                    <partial name="_Notification" />
                    @RenderBody()
                </main>
            </div>
        </div>
        @{
            if (User.Identity.IsAuthenticated)
            {
                <div class="container pb-5">
                    <h2 class="mb-4">Funzioni per dipendenti</h2>
                    <div class="row row-cols-4">
                        <div class="col">
                            <a class="text-decoration-none" asp-controller="Animale" asp-action="Create">
                                <div id="registerPet" class="position-relative functionSection">
                                    <p class="bg-white fw-bold d-inline-block rounded-3 py-1 px-2 mt-2 ms-2 mb-0">Registra un animale</p>
                                </div>
                            </a>
                        </div>
                        <div class="col" style="height: 200px">
                            <a class="text-decoration-none" asp-controller="Visita" asp-action="Create">
                                <div id="visitaSection" class="position-relative functionSection">
                                    <p class="bg-white fw-bold d-inline-block rounded-3 py-1 px-2 mt-2 ms-2 mb-0">Registra una visita</p>
                                </div>
                            </a>
                        </div>
                        <div class="col">
                            <a class="text-decoration-none" asp-controller="Vendita" asp-action="Create">
                                <div id="venditaSection" class="position-relative functionSection">
                                    <p class="bg-white fw-bold d-inline-block rounded-3 py-1 px-2 mt-2 ms-2 mb-0">Effettua vendita</p>
                                </div>
                            </a>
                        </div>
                        <div class="col">
                            <a class="text-decoration-none" asp-controller="Prodotto" asp-action="Index">
                                <div id="prodottiSection" class="position-relative functionSection">
                                    <p class="bg-white fw-bold d-inline-block rounded-3 py-1 px-2 mt-2 ms-2 mb-0">Visualizza prodotti</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            }
        }

        @* <footer class="border-top footer text-muted">
        <div class="container">
        &copy; 2024 - Sanitario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        </footer> *@
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Sanitario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sanitario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/Sanitario.styles.css" asp-append-version="true" />
</head>
    @{
        // Ottieni l'URL corrente
        var currentUrl = Context.Request.Path;
        // Definisci una variabile per l'ID dell'elemento
        string selectedBg = "yellowSplash";
        string textColor = "#22306B";
        // Verifica se l'URL contiene un certo modello e modifica l'ID di conseguenza
        if (currentUrl.Value.Contains("Animale"))
        {
            selectedBg = "animaleSplash";
        }
        else if (currentUrl.Value.Contains("Visita"))
        {
            selectedBg = "visitaSplash";
        }
        else if (currentUrl.Value.Contains("Vendita"))
        {
            selectedBg = "venditaSplash";
        }
        else if (currentUrl.Value.Contains("Prodotto"))
        {
            selectedBg = "prodottiSplash";
        }
        else
        {
            selectedBg = "yellowSplash";
            textColor = "#22306B";
        }
    }
<body class="p-5" style="color: @textColor">
    <div id=@selectedBg class="mx-5 my-3 rounded bg-white" style="min-height: 75vh;">
        <header class="mb-3">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navBg">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="/imgs/site/logo.png" width="100" />
                        </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link primaryText" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @{
                                if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link primaryText" asp-area="" asp-controller="Dipendente" asp-action="BackOffice">BackOffice</a>
                                }
                            }
                        </ul>
                        @{
                            if (!User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link primaryText" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            }
                            else
                            {
                                <a class="nav-link primaryText" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            }
                        }
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="py-3">
                <partial name="_Notification" />
                @RenderBody()
            </main>
        </div>

         @* <footer class="border-top footer text-muted">
             <div class="container">
                 &copy; 2024 - Sanitario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
             </div>
         </footer> *@
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Sanitario/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}